version: '3'

services:
  php:
    image: php:8.2-apache
    volumes:
      - ./test:/var/www/html
      - ./src:/var/www/src
      - ./vendor:/var/www/vendor
    ports:
      - 9180:80
    container_name: php8.2-trial
