version: '3'

services:
  php:
    image: php:8.2-apache
    volumes:
      - ./test:/var/www/html
      - ./src:/var/www/src
      - ./vendor:/var/www/vendor
    ports:
      - 9180:80
    container_name: php8.2-trial
    environment:
      - VITE_HOST=http://vite
      - VITE_HOST_WEB=http://localhost
      - VITE_PORT=${VITE_PORT:-5173}

  vite:
    image: node:22
    container_name: vite
    working_dir: /app
    volumes:
      - ./:/app
      - /node_modules
    command: sh -c "npm run dev"
    ports:
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    environment:
      - VITE_HOST=0.0.0.0
    networks:
      - php

networks:
  php:
    driver: bridge
